export const transactionData = [
  {
    id: 1,
    name: "Demo",
    description: "Demo user",
    amount: 1,
    currency: "TRY",
    date: "02.04.2020",
  },
  {
    id: 2,
    name: "Test",
    description: "Test user",
    amount: 2,
    currency: "USD",
    date: "06.02.2020",
  },
  {
    id: 3,
    name: "Admin",
    description: "Admin user",
    amount: 3,
    currency: "EUR",
    date: "01.03.2020",
  },
  {
    id: 4,
    name: "None",
    description: "None user",
    amount: 4,
    currency: "EUR",
    date: "07.03.2020",
  },
  {
    id: 5,
    name: "Demo",
    description: "Demo user",
    amount: 1,
    currency: "TRY",
    date: "02.04.2020",
  },
  {
    id: 6,
    name: "aaa",
    description: "aaa",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 7,
    name: "aaa",
    description: "aaa",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 8,
    name: "aaaa",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 9,
    name: "aaaa",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 10,
    name: "aaaa",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 11,
    name: "aaaa",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 12,
    name: "aaaa",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 13,
    name: "aaaa",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 14,
    name: "aaaaa",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
  {
    id: 15,
    name: "dddd",
    description: "",
    date: "19.09.2020",
    amount: 0,
    currency: "TRY",
  },
];
